### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bulbil** [seongjaelee/notational-velocity#49]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: linux 4.5.1-1-ARCH
**Thrown From**: [nvatom](https://github.com/seongjaelee/nvatom) package, v0.10.0
### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /home/bulbil/.atom/packages/nvatom/node_modules/docquery/node_modules/lunr/lunr.js:968

RangeError: Maximum call stack size exceeded
    at [object Object].<anonymous> (/home/bulbil/.atom/packages/nvatom/node_modules/docquery/node_modules/lunr/lunr.js:968:34)
    at Array.forEach (native)
    at [object Object].lunr.Index.add (/home/bulbil/.atom/packages/nvatom/node_modules/docquery/node_modules/lunr/lunr.js:964:16)
    at DocQuery.addDocument (/home/bulbil/.atom/packages/nvatom/node_modules/docquery/lib/DocQuery.js:85:24)
    at FSWatcher.<anonymous> (/home/bulbil/.atom/packages/nvatom/node_modules/docquery/lib/DocQuery.js:63:13)
    at emitTwo (events.js:87:13)
    at FSWatcher.emit (events.js:172:7)
    at FSWatcher.<anonymous> (/home/bulbil/.atom/packages/nvatom/node_modules/chokidar/index.js:171:15)
    at FSWatcher._emit (/home/bulbil/.atom/packages/nvatom/node_modules/chokidar/index.js:212:5)
    at FSWatcher.NodeFsHandler._handleFile (/home/bulbil/.atom/packages/nvatom/node_modules/chokidar/lib/nodefs-handler.js:275:10)
    at FSWatcher.<anonymous> (/home/bulbil/.atom/packages/nvatom/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -0:04.1.0 nvatom:toggle (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "themes": [
      "arc-darker"
    ]
  },
  "nvatom": {
    "directory": "~/Dropbox/notational"
  }
}
```
### Installed Packages

``` coffee
# User
nvatom, v0.10.0

# Dev
No dev packages
```

**Comment by seongjaelee** [comment]
I think there is some infinite recursive call somewhere, but with this info, it is hard to figure out what is wrong... How is the file/directory structure is? Do you have symbolic links?
