### ISSUE TITLE
Uncaught Error: Cannot find module 'docquery'

### ISSUE THREAD

**Issue by ghost** [seongjaelee/notational-velocity#54]
1. install nvatom branch topic-35
2. try to run nvatom
3. it seems this is the problem. removing this line allows nvatom to load: https://github.com/seongjaelee/nvatom/blob/topic-35/lib/notational-velocity-view.coffee#L5

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [nvatom](https://github.com/seongjaelee/nvatom) package, v0.11.0
### Stack Trace

Uncaught Error: Cannot find module 'docquery'

```
At module.js:340

Error: Cannot find module 'docquery'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/nick/.atom/packages/nvatom/lib/notational-velocity-view.coffee:5:12)
    at Object.<anonymous> (/home/nick/.atom/packages/nvatom/lib/notational-velocity-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.createView (/home/nick/.atom/packages/nvatom/lib/notational-velocity.coffee:66:32)
    at atom-workspace.subscriptions.add.atom.commands.add.nvatom:toggle (/home/nick/.atom/packages/nvatom/lib/notational-velocity.coffee:38:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:54.2.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:47.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:47 core:paste (atom-text-editor.editor.is-focused)
     -1:46.6.0 core:undo (atom-text-editor.editor.is-focused)
     -1:43 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:42 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:35.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:35.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:34.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:34.4.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:33.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:26.9.0 nvatom:toggle (atom-text-editor.editor.is-focused)
  2x -1:25.7.0 core:close (atom-text-editor.editor.is-focused)
  2x -1:23.8.0 nvatom:toggle (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -1:18 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.8.0 nvatom:toggle (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "automaticallyUpdate": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "about",
      "background-tips",
      "welcome",
      "update-package-dependencies",
      "styleguide",
      "deprecation-cop",
      "exception-reporting",
      "metrics",
      "package-generator",
      "archive-view",
      "merge-conflicts",
      "linter"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".remarkrc"
    ],
    "packagesWithKeymapsDisabled": [],
    "projectHome": "/home/nick/Projects",
    "restorePreviousWindowsOnStart": false
  },
  "nvatom": {
    "directory": "/home/nick/Notes"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
block-travel, v1.0.4
external-open, v0.6.3
file-icons, v1.7.15
highlight-selected, v0.11.2
linter-shellcheck, v1.2.0
minimap, v4.24.6
minimap-bookmarks, v0.3.1
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-highlight-selected, v4.4.0
minimap-selection, v4.4.0
nvatom, v0.11.0
open-sesame, v0.4.0
project-plus, v0.9.0
recent-files-fuzzy-finder, v0.2.4
sync-settings, v0.7.2
tab-title, v0.3.3
tabs-to-spaces, v1.0.2
toggle-packages, v1.1.0

# Dev
No dev packages
```

**Comment by seongjaelee** [comment]
Thanks a lot! I was working on cached node_modules, so I couldn't be able to detect this problem.
Fixed.
https://github.com/seongjaelee/nvatom/commit/4eb6ada48aec262e482a4e1ff07c55f48542fc04
